local addonName, BAG = ...
BAG.Guides.Gold.Dailies = {title = "Daily Quests for Gold", faction = "Both", steps = {BAG.Parser:Note("Complete daily quests at level 70 for consistent gold income"), BAG.Parser:Note("Shattrath, Skettis, Netherwing, and Ogri'la dailies are excellent")}}
