local addonName, BAG = ...
BAG.Guides.Gold.Farming = {title = "Gold Farming Routes", faction = "Both", steps = {BAG.Parser:Note("Farm mobs in high-level zones for gold and materials"), BAG.Parser:Note("Popular spots: Stratholme, Dire Maul, Outland dungeons")}}
