local addonName, BAG = ...
BAG.Guides.Gold.Professions = {title = "Gold from Professions", faction = "Both", steps = {BAG.Parser:Note("Use gathering professions to farm materials"), BAG.Parser:Note("Sell on Auction House for profit")}}
