local addonName, BAG = ...
BAG.Guides.Professions.Blacksmithing = {title = "Blacksmithing 1-375", faction = "Both", profession = "Blacksmithing", steps = {BAG.Parser:Note("Blacksmithing creates armor and weapons"), BAG.Parser:Note("Requires Mining for materials"), BAG.Parser:Note("Train and craft items to level up")}}
