local addonName, BAG = ...
BAG.Guides.Professions.Engineering = {title = "Engineering 1-375", faction = "Both", profession = "Engineering", steps = {BAG.Parser:Note("Engineering creates gadgets and explosives")}}
