local addonName, BAG = ...
BAG.Guides.Professions.FirstAid = {title = "First Aid 1-375", faction = "Both", profession = "First Aid", steps = {BAG.Parser:Note("First Aid creates bandages for healing")}}
