local addonName, BAG = ...
BAG.Guides.Professions.Fishing = {title = "Fishing 1-375", faction = "Both", profession = "Fishing", steps = {BAG.Parser:Note("Fishing is relaxing and provides materials for Cooking")}}
