local addonName, BAG = ...
BAG.Guides.Professions.Leatherworking = {title = "Leatherworking 1-375", faction = "Both", profession = "Leatherworking", steps = {BAG.Parser:Note("Leatherworking creates leather and mail armor")}}
